version: '3.8'

services:
  mysql:
    image: mysql:5.7
    container_name: obs_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: obs
      MYSQL_USER: obsuser
      MYSQL_PASSWORD: obspassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - obs_network

volumes:
  mysql_data:

networks:
  obs_network:
    driver: bridge
